services:
  db:
    build: 
      context: ./MySQL
      dockerfile: dockerfile
    container_name: university
    restart: always
    ports:
      - 5500:3306
    volumes:
      - ./Config/mysql:/var/lib/mysql
    hostname: owner
    networks:
      - eam_apps
    healthcheck:
        test: ["CMD","mysql", "-u", "shanda", "-pShanda123*"]
        interval: 30s
        timeout: 10s
        retries: 5
# --------------------------------------------------------------------
  # - The adminer is a tool for managing content in databases.
  adminer:
    image: adminer
    container_name: adminer_exam
    restart: always
    ports:
      - 8000:8080
    networks:
      - eam_apps
# --------------------------------------------------------------------

networks:
  eam_apps:
      driver: bridge
      name: eam_apps